data:
  data_path: '../KITTI'
  dataset: 'KITTI'
mode:
  train: no
  val: no
  test: yes

train:
  no_cuda: no
  batch_size: 1
  model:
    backbone: 'MaskRCNN'
    pose_net:
    shape_net:
    renderer:
val:
  batch_size: 1

test:
  no_cuda: no
  batch_size: 1
  model: 
    backbone: 'MaskRCNN'
    pose_net:
    shape_net:
    renderer:
